// src/react/components/MessageItem.tsx
/**
 * React - MessageItem Component
 */

import type { NotificationItem } from '../../types'
import React, { useMemo } from 'react'

interface MessageItemProps {
  item: NotificationItem
  onDismiss: (id: string) => void
}

export function MessageItem({ item, onDismiss }: MessageItemProps) {
  const classList = useMemo(() => {
    const classes = ['ldesign-message', `ldesign-message--${item.variant}`, item.className]
    if (item.data?.center) {
      classes.push('ldesign-message--center')
    }
    return classes.filter(Boolean).join(' ')
  }, [item.variant, item.className, item.data?.center])

  const showIcon = item.icon !== false
  const showClose = item.data?.showClose === true

  const iconText = useMemo(() => {
    if (typeof item.icon === 'string') {
      return item.icon
    }

    const defaultIcons: Record<string, string> = {
      success: '✓',
      error: '✕',
      warning: '⚠',
      info: 'ℹ',
    }

    return defaultIcons[item.variant] || ''
  }, [item.icon, item.variant])

  const handleClick = () => {
    item.onClick(item.id)
  }

  const handleClose = (e: React.MouseEvent) => {
    e.stopPropagation()
    onDismiss(item.id)
  }

  return (
    <div className={classList} data-id={item.id} style={item.style} onClick={handleClick}>
      <div className="ldesign-message-content">
        {showIcon && <span className="ldesign-notification-icon">{iconText}</span>}
        <span className="ldesign-message-text">{item.message}</span>
      </div>
      {showClose && (
        <button className="ldesign-notification-close" aria-label="Close" onClick={handleClose}>
          ×
        </button>
      )}
    </div>
  )
}

// src/vue/components/MessageItem.vue
<template>
  <div
    :class="classList"
    :data-id="item.id"
    :style="item.style"
    @click="handleClick"
  >
    <div class="ldesign-message-content">
      <span v-if="showIcon" class="ldesign-notification-icon">
        {{ iconText }}
      </span>
      <span class="ldesign-message-text">
        {{ item.message }}
      </span>
    </div>
    <button
      v-if="showClose"
      class="ldesign-notification-close"
      aria-label="Close"
      @click.stop="handleClose"
    >
      ×
    </button>
  </div>
</template>

<script setup lang="ts">
import type { NotificationItem } from '../../types'
import { computed } from 'vue'

interface Props {
  item: NotificationItem
}

interface Emits {
  (e: 'dismiss', id: string): void
}

const props = defineProps<Props>()
const emit = defineEmits<Emits>()

const classList = computed(() => [
  'ldesign-message',
  `ldesign-message--${props.item.variant}`,
  props.item.className,
  { 'ldesign-message--center': props.item.data?.center },
])

const showIcon = computed(() => props.item.icon !== false)

const showClose = computed(() => props.item.data?.showClose === true)

const iconText = computed(() => {
  if (typeof props.item.icon === 'string') {
    return props.item.icon
  }

  const defaultIcons: Record<string, string> = {
    success: '✓',
    error: '✕',
    warning: '⚠',
    info: 'ℹ',
  }

  return defaultIcons[props.item.variant] || ''
})

function handleClick() {
  props.item.onClick(props.item.id)
}

function handleClose() {
  emit('dismiss', props.item.id)
}
</script>
